import assert from "node:assert/strict";
import test from "node:test";
import { existsSync } from "node:fs";
const url = new URL("../src/lib/agent-request.ts", import.meta.url);
const org = "c447e3bc-70aa-4a69-b176-d322c6ab42d8";
const request = (body, origin = "https://app.test") => new Request(`https://app.test/api/organizations/${org}/agents`, { method: "POST", headers: { origin, host: "app.test", "content-type": "application/json" }, body: JSON.stringify(body) });
test("agent request authorizes owned organization before writing and keeps instructions out of responses", async () => {
 assert.ok(existsSync(url), "authorized agent handler missing");
 const { handleAgentRequest } = await import(url);
 let writes = 0;
 const deps = { getAccess: async () => ({ supabase: {}, userId: "user_owner" }), findOrganization: async (_db, userId, id) => { assert.equal(userId, "user_owner"); assert.equal(id, org); return { data: { id: org }, error: null }; }, listAgents: async () => ({ data: [], error: null }), insertAgent: async (_db, id, input) => { writes++; assert.equal(id, org); assert.deepEqual(input, { name: "Test", instructions: "Private" }); return { data: { id: "agent-id", name: "Test" }, error: null }; } };
 const res = await handleAgentRequest(request({ name: "Test", instructions: "Private", organization_id: "other" }), org, deps);
 assert.equal(res.status, 201);
 assert.deepEqual(await res.json(), { agent: { id: "agent-id", name: "Test" } });
 assert.equal(writes, 1);
 assert.equal((await handleAgentRequest(request({ name: "Test", instructions: "Private" }, "https://evil.test"), org, deps)).status, 403);
 assert.equal((await handleAgentRequest(request({ name: "Test", instructions: "Private" }), org, { ...deps, findOrganization: async () => ({ data: null, error: null }) })).status, 404);
 assert.equal((await handleAgentRequest(request({ name: "Test", instructions: "Private" }), org, { ...deps, getAccess: async () => ({ error: "Forbidden", status: 403 }) })).status, 403);
 assert.equal((await handleAgentRequest(request({ name: "Test", instructions: "" }), org, deps)).status, 400);
 assert.equal((await handleAgentRequest(request({}), "not-uuid", deps)).status, 404);
 assert.equal(writes, 1);
 const list = await handleAgentRequest(new Request(`https://app.test/api/organizations/${org}/agents`), org, deps);
 assert.equal(list.status, 200);
 assert.deepEqual(await list.json(), { agents: [] });
 assert.equal(list.headers.get("cache-control"), "private, no-store");
 const unavailable = await handleAgentRequest(request({ name: "Test", instructions: "Private" }), org, { ...deps, insertAgent: async () => { throw new Error("sensitive DB error"); } });
 assert.equal(unavailable.status, 503);
 assert.doesNotMatch(await unavailable.text(), /sensitive|Private/);
});
