import assert from "node:assert/strict";
import test from "node:test";
import { existsSync, readFileSync } from "node:fs";
const source = path => { const url = new URL(`../${path}`, import.meta.url); assert.ok(existsSync(url), `${path} missing`); return readFileSync(url, "utf8"); };
test("agents migration limits grants and isolates active owners of non-archived organizations", () => {
 const sql = source("supabase/migrations/20261008000300_organization_agents.sql");
 assert.match(sql, /references public.organizations \(id\) on delete restrict/);
 assert.match(sql, /enable row level security/);
 assert.match(sql, /grant select \(id, organization_id, name, created_at\)/);
 assert.match(sql, /grant insert \(organization_id, name, instructions\)/);
 assert.doesNotMatch(sql, /grant select on|grant update|grant delete|security definer/i);
 assert.match(sql, /between 1 and 20000/);
 for (const action of ["select", "insert"]) assert.match(sql, new RegExp(`create policy agents_${action}_owned`));
 assert.equal((sql.match(/organization.owner_clerk_user_id = \(select auth.jwt\(\) ->> 'sub'\)/g) ?? []).length, 2);
 assert.equal((sql.match(/organization.archived_at is null/g) ?? []).length, 2);
 assert.equal((sql.match(/platform_user.role in \('owner', 'admin'\)/g) ?? []).length, 2);
 assert.equal((sql.match(/platform_user.status = 'active'/g) ?? []).length, 2);
});
test("agent UI and API wire authorized scopes without exposing instructions or unsupported features", () => {
 const route = source("src/app/api/organizations/[id]/agents/route.ts");
 assert.match(route, /handleAgentRequest/);
 assert.match(route, /getOrganizationAccess/);
 assert.match(route, /findOrganization/);
 const list = source("src/app/organizations/[id]/agents/page.tsx");
 assert.match(list, /findOrganization\(access.supabase, access.userId, id\)/);
 assert.match(list, /listAgents\(access.supabase, id\)/);
 assert.match(list, /Nenhum agente/);
 const detail = source("src/app/organizations/[id]/agents/[agentId]/page.tsx");
 assert.match(detail, /findOrganization\(access.supabase, access.userId, id\)/);
 assert.match(detail, /findAgent\(access.supabase, id, agentId\)/);
 assert.doesNotMatch(detail, /\.instructions|chat|documentos/i);
 const form = source("src/app/organizations/[id]/agents/agent-form.tsx");
 assert.match(form, /name="instructions"/);
 assert.match(form, /busy.current/);
 assert.match(form, /disabled=\{pending\}/);
 assert.match(source("src/app/organizations/[id]/page.tsx"), /\/agents/);
 source("src/app/organizations/[id]/agents/loading.tsx");
 source("src/app/organizations/[id]/agents/error.tsx");
});
